# For more information on the configuration options,
#  see the docs and the demo in the assets folder

# points to page outlining you site's privacy policy
privacyUrl: '/page/privacy'

# In the UK implicit concent is perfectly okay - check what is needed in your region.
explicitConsent: 'false'

# can be shown at the 'top' or the 'bottom of the page.
cookieLocation: 'top'

# used to list which cookies your site is using.
cookieScripts: 'Google Analytics'

# Banner background color.
backgroundColor: '#52b54a'

# Banner link color.
linkColor: '#ffffff'

# how long to show the warning in seconds
showTime: 20